export const mockTickets = [
  {
    id: "1",
    description: "Leaky faucet in apartment 3B kitchen",
    severity: "medium",
    status: "open",
    created_at: "2024-01-15T10:30:00Z",
    updated_at: "2024-01-15T10:30:00Z",
    room_number: "3B",
    tenant_name: "Sarah Johnson",
    category: "plumbing",
    assigned_to: "Mike Rodriguez",
  },
  {
    id: "2",
    description: "Broken elevator on floors 5-8",
    severity: "high",
    status: "in_progress",
    created_at: "2024-01-14T14:20:00Z",
    updated_at: "2024-01-15T09:15:00Z",
    building_area: "Main Elevator Bank",
    category: "mechanical",
    assigned_to: "David Chen",
  },
  {
    id: "3",
    description: "Air conditioning not working in unit 7A",
    severity: "high",
    status: "open",
    created_at: "2024-01-15T16:45:00Z",
    updated_at: "2024-01-15T16:45:00Z",
    room_number: "7A",
    tenant_name: "Robert Kim",
    category: "hvac",
    assigned_to: null,
  },
  {
    id: "4",
    description: "Flickering lights in lobby",
    severity: "low",
    status: "resolved",
    created_at: "2024-01-12T11:00:00Z",
    updated_at: "2024-01-13T15:30:00Z",
    building_area: "Main Lobby",
    category: "electrical",
    assigned_to: "Lisa Park",
  },
  {
    id: "5",
    description: "Garbage disposal jammed in unit 2C",
    severity: "medium",
    status: "in_progress",
    created_at: "2024-01-14T08:15:00Z",
    updated_at: "2024-01-15T12:00:00Z",
    room_number: "2C",
    tenant_name: "Emily Davis",
    category: "appliance",
    assigned_to: "Mike Rodriguez",
  },
  {
    id: "6",
    description: "Parking garage gate malfunction",
    severity: "medium",
    status: "open",
    created_at: "2024-01-15T07:30:00Z",
    updated_at: "2024-01-15T07:30:00Z",
    building_area: "Parking Garage",
    category: "security",
    assigned_to: null,
  },
]

export const mockIncidents = [
  {
    id: "1",
    description: "Water leak in basement causing flooding",
    severity: "critical",
    status: "active",
    created_at: "2024-01-15T06:00:00Z",
    affected_units: ["B1", "B2", "1A", "1B"],
    estimated_resolution: "2024-01-16T18:00:00Z",
  },
  {
    id: "2",
    description: "Power outage in east wing",
    severity: "high",
    status: "resolved",
    created_at: "2024-01-14T20:30:00Z",
    affected_units: ["4E", "5E", "6E", "7E", "8E"],
    resolved_at: "2024-01-15T02:15:00Z",
  },
]

export const mockServices = [
  {
    id: "1",
    svc_type: "cleaning",
    description: "Deep cleaning service for unit 5B",
    status: "scheduled",
    created_at: "2024-01-10T14:00:00Z",
    scheduled_date: "2024-01-18T10:00:00Z",
    tenant_name: "Michael Brown",
    room_number: "5B",
  },
  {
    id: "2",
    svc_type: "pest_control",
    description: "Monthly pest control treatment",
    status: "completed",
    created_at: "2024-01-08T09:00:00Z",
    completed_date: "2024-01-12T11:30:00Z",
    building_area: "All Common Areas",
  },
  {
    id: "3",
    svc_type: "landscaping",
    description: "Garden maintenance and tree trimming",
    status: "in_progress",
    created_at: "2024-01-13T16:00:00Z",
    building_area: "Courtyard and Front Entrance",
  },
]

export const mockDeliveries = [
  {
    id: "del_001",
    svc_type: "delivery",
    description: "Amazon package for unit 3B",
    status: "pending",
    created_at: "2024-01-10T09:00:00Z",
    expected_delivery_date: "2024-01-12T17:00:00Z",
    requester_name: "Sarah Johnson",
    unit_id: "3B",
    delivery_company: "Amazon",
    tracking_number: "1Z999AA1234567890",
  },
  {
    id: "del_002",
    svc_type: "delivery",
    description: "Furniture delivery for unit 7A",
    status: "approved",
    created_at: "2024-01-08T14:30:00Z",
    expected_delivery_date: "2024-01-14T10:00:00Z",
    requester_name: "Robert Kim",
    unit_id: "7A",
    delivery_company: "West Elm",
    tracking_number: "WE123456789",
  },
  {
    id: "del_003",
    svc_type: "delivery",
    description: "Grocery delivery for unit 2C",
    status: "completed",
    created_at: "2024-01-13T11:00:00Z",
    expected_delivery_date: "2024-01-13T15:00:00Z",
    completed_at: "2024-01-13T14:45:00Z",
    requester_name: "Emily Davis",
    unit_id: "2C",
    delivery_company: "Instacart",
    tracking_number: "IC987654321",
  },
  {
    id: "del_004",
    svc_type: "delivery",
    description: "Medical supplies for unit 5B",
    status: "pending",
    created_at: "2024-01-09T16:20:00Z",
    expected_delivery_date: "2024-01-11T12:00:00Z",
    requester_name: "Michael Brown",
    unit_id: "5B",
    delivery_company: "CVS Pharmacy",
    tracking_number: "CVS445566778",
  },
  {
    id: "del_005",
    svc_type: "delivery",
    description: "Electronics delivery for unit 4A",
    status: "approved",
    created_at: "2024-01-12T08:15:00Z",
    expected_delivery_date: "2024-01-15T16:00:00Z",
    requester_name: "Jessica Wilson",
    unit_id: "4A",
    delivery_company: "Best Buy",
    tracking_number: "BB112233445",
  },
  {
    id: "del_006",
    svc_type: "delivery",
    description: "Food delivery for unit 1D",
    status: "cancelled",
    created_at: "2024-01-14T19:30:00Z",
    expected_delivery_date: "2024-01-14T20:30:00Z",
    cancelled_at: "2024-01-14T20:00:00Z",
    requester_name: "David Martinez",
    unit_id: "1D",
    delivery_company: "DoorDash",
    tracking_number: "DD556677889",
  },
]

export const mockTenants = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    phone: "(555) 123-4567",
    unit: "3B",
    lease_start: "2023-06-01",
    lease_end: "2024-05-31",
    rent_amount: 156800,
    status: "active",
    emergency_contact: "John Johnson - (555) 123-4568",
  },
  {
    id: "2",
    name: "Robert Kim",
    email: "robert.kim@email.com",
    phone: "(555) 234-5678",
    unit: "7A",
    lease_start: "2023-09-01",
    lease_end: "2024-08-31",
    rent_amount: 179200,
    status: "active",
    emergency_contact: "Grace Kim - (555) 234-5679",
  },
  {
    id: "3",
    name: "Emily Davis",
    email: "emily.davis@email.com",
    phone: "(555) 345-6789",
    unit: "2C",
    lease_start: "2023-03-15",
    lease_end: "2024-03-14",
    rent_amount: 145600,
    status: "active",
    emergency_contact: "Mark Davis - (555) 345-6790",
  },
  {
    id: "4",
    name: "Michael Brown",
    email: "michael.brown@email.com",
    phone: "(555) 456-7890",
    unit: "5B",
    lease_start: "2023-11-01",
    lease_end: "2024-10-31",
    rent_amount: 162400,
    status: "active",
    emergency_contact: "Lisa Brown - (555) 456-7891",
  },
  {
    id: "5",
    name: "Jessica Wilson",
    email: "jessica.wilson@email.com",
    phone: "(555) 567-8901",
    unit: "4A",
    lease_start: "2023-07-01",
    lease_end: "2024-06-30",
    rent_amount: 173600,
    status: "notice_given",
    emergency_contact: "Tom Wilson - (555) 567-8902",
  },
  {
    id: "6",
    name: "David Martinez",
    email: "david.martinez@email.com",
    phone: "(555) 678-9012",
    unit: "1D",
    lease_start: "2023-12-01",
    lease_end: "2024-11-30",
    rent_amount: 140000,
    status: "active",
    emergency_contact: "Maria Martinez - (555) 678-9013",
  },
]

export const mockAnnouncements = [
  {
    id: "1",
    title: "Scheduled Maintenance - Water System",
    content:
      "**Important Notice**\n\nWe will be performing scheduled maintenance on the building's water system on **Saturday, January 20th from 9:00 AM to 2:00 PM**.\n\n**What to expect:**\n- Water service will be temporarily interrupted\n- Please store water in advance for drinking and cooking\n- Maintenance will affect all units\n\n**Contact Information:**\nFor questions, please contact the management office at (555) 123-0000.\n\nThank you for your patience.",
    created_at: "2024-01-15T10:00:00Z",
    priority: "high",
    expires_at: "2024-01-21T00:00:00Z",
  },
  {
    id: "2",
    title: "New Recycling Guidelines",
    content:
      "**Updated Recycling Program**\n\nStarting February 1st, we're implementing new recycling guidelines to better serve our community:\n\n**New Guidelines:**\n- Separate glass from other recyclables\n- Clean all containers before disposal\n- No plastic bags in recycling bins\n\n**Recycling Schedule:**\n- Monday & Thursday: Regular recycling\n- Saturday: Glass recycling only\n\nThank you for helping keep our community green!",
    created_at: "2024-01-12T14:30:00Z",
    priority: "medium",
    expires_at: "2024-02-15T00:00:00Z",
  },
  {
    id: "3",
    title: "Holiday Office Hours",
    content:
      "**Management Office Holiday Schedule**\n\nPlease note our adjusted hours for the upcoming holiday:\n\n- **January 15th (MLK Day):** Closed\n- **Emergency Contact:** (555) 123-0001\n\nRegular office hours resume Tuesday, January 16th at 9:00 AM.\n\nHappy Holiday!",
    created_at: "2024-01-10T16:00:00Z",
    priority: "low",
    expires_at: "2024-01-16T00:00:00Z",
  },
]

export const mockDashboardStats = {
  totalTickets: 24,
  openTickets: 12,
  inProgressTickets: 6,
  resolvedTickets: 6,
  totalTenants: 48,
  occupancyRate: 94,
  maintenanceRequests: 18,
  avgResolutionTime: 2.3,
  monthlyRevenue: 7996800,
  pendingPayments: 3,
  activeIncidents: 1,
  scheduledServices: 5,
  satisfactionRate: 4.7, // out of 5 stars
  responseTime: 2.4,
  resolvedToday: 8,
  criticalIssues: 2,
  upcomingInspections: 12,
  renewalsThisMonth: 6,
  overdueDeliveries: 2,
  totalDeliveries: 6,
  avgDeliveryTime: 1.2, // days
}

export const mockChartData = {
  ticketsByMonth: [
    { month: "Aug", tickets: 15, resolved: 12, open: 3 },
    { month: "Sep", tickets: 22, resolved: 18, open: 4 },
    { month: "Oct", tickets: 18, resolved: 15, open: 3 },
    { month: "Nov", tickets: 28, resolved: 22, open: 6 },
    { month: "Dec", tickets: 19, resolved: 16, open: 3 },
    { month: "Jan", tickets: 24, resolved: 16, open: 8 },
  ],
  ticketsByCategory: [
    { category: "Plumbing", count: 8, fill: "#3b82f6" },
    { category: "Electrical", count: 5, fill: "#ef4444" },
    { category: "HVAC", count: 6, fill: "#10b981" },
    { category: "Appliance", count: 3, fill: "#f59e0b" },
    { category: "Other", count: 2, fill: "#8b5cf6" },
  ],
  revenueByMonth: [
    { month: "Aug", revenue: 7756800, expenses: 700000 },
    { month: "Sep", revenue: 7907200, expenses: 884800 },
    { month: "Oct", revenue: 7828800, expenses: 627200 },
    { month: "Nov", revenue: 7957600, expenses: 778400 },
    { month: "Dec", revenue: 7873600, expenses: 907200 },
    { month: "Jan", revenue: 7996800, expenses: 789600 },
  ],
  occupancyTrend: [
    { month: "Aug", rate: 92 },
    { month: "Sep", rate: 95 },
    { month: "Oct", rate: 93 },
    { month: "Nov", rate: 96 },
    { month: "Dec", rate: 94 },
    { month: "Jan", rate: 94 },
  ],
}

export const mockRecentActivities = [
  {
    id: "1",
    type: "ticket_created",
    description: "New maintenance request: Leaky faucet in 3B",
    timestamp: "2024-01-15T16:30:00Z",
    user: "Sarah Johnson",
    priority: "medium",
  },
  {
    id: "2",
    type: "ticket_resolved",
    description: "Resolved: Flickering lights in lobby",
    timestamp: "2024-01-15T14:20:00Z",
    user: "Lisa Park",
    priority: "low",
  },
  {
    id: "3",
    type: "payment_received",
    description: "Rent payment received from unit 7A",
    timestamp: "2024-01-15T12:15:00Z",
    user: "Robert Kim",
    amount: 179200,
  },
  {
    id: "4",
    type: "inspection_scheduled",
    description: "Annual inspection scheduled for unit 2C",
    timestamp: "2024-01-15T10:45:00Z",
    user: "Property Manager",
    date: "2024-01-22T10:00:00Z",
  },
  {
    id: "5",
    type: "lease_renewal",
    description: "Lease renewal signed for unit 5B",
    timestamp: "2024-01-15T09:30:00Z",
    user: "Michael Brown",
    duration: "12 months",
  },
]

export const mockUpcomingTasks = [
  {
    id: "1",
    title: "Monthly fire safety inspection",
    dueDate: "2024-01-18T09:00:00Z",
    priority: "high",
    assignee: "David Chen",
    category: "safety",
  },
  {
    id: "2",
    title: "HVAC filter replacement - All units",
    dueDate: "2024-01-20T10:00:00Z",
    priority: "medium",
    assignee: "Mike Rodriguez",
    category: "maintenance",
  },
  {
    id: "3",
    title: "Lease renewal meeting with tenant 4A",
    dueDate: "2024-01-19T14:00:00Z",
    priority: "high",
    assignee: "Property Manager",
    category: "leasing",
  },
  {
    id: "4",
    title: "Parking lot cleaning and maintenance",
    dueDate: "2024-01-21T08:00:00Z",
    priority: "low",
    assignee: "Maintenance Team",
    category: "cleaning",
  },
]

export const mockEquipmentData = [
  {
    id: "eq_001",
    name: "Main HVAC System - Building A",
    type: "hvac",
    location: "Rooftop - Building A",
    installDate: "2019-03-15",
    lastMaintenance: "2024-01-10T10:00:00Z",
    nextScheduledMaintenance: "2024-02-10T10:00:00Z",
    condition: "good",
    utilizationHours: 8760, // hours per year
    maintenanceHistory: [
      { date: "2024-01-10", type: "filter_replacement", cost: 15000 },
      { date: "2023-11-15", type: "coil_cleaning", cost: 25000 },
      { date: "2023-08-20", type: "belt_replacement", cost: 8000 },
    ],
  },
  {
    id: "eq_002",
    name: "Elevator System - Main",
    type: "mechanical",
    location: "Central Elevator Shaft",
    installDate: "2018-06-20",
    lastMaintenance: "2024-01-05T14:00:00Z",
    nextScheduledMaintenance: "2024-02-05T14:00:00Z",
    condition: "fair",
    utilizationHours: 6000,
    maintenanceHistory: [
      { date: "2024-01-05", type: "cable_inspection", cost: 35000 },
      { date: "2023-10-12", type: "motor_service", cost: 85000 },
      { date: "2023-07-08", type: "safety_check", cost: 20000 },
    ],
  },
  {
    id: "eq_003",
    name: "Water Heater - Building B",
    type: "plumbing",
    location: "Basement - Building B",
    installDate: "2020-01-10",
    lastMaintenance: "2023-12-20T09:00:00Z",
    nextScheduledMaintenance: "2024-03-20T09:00:00Z",
    condition: "excellent",
    utilizationHours: 8760,
    maintenanceHistory: [
      { date: "2023-12-20", type: "anode_replacement", cost: 12000 },
      { date: "2023-09-15", type: "tank_flush", cost: 6000 },
      { date: "2023-06-10", type: "thermostat_check", cost: 4000 },
    ],
  },
]

export const mockFailurePredictions = [
  {
    equipmentId: "eq_001",
    equipmentName: "Main HVAC System - Building A",
    failureType: "Compressor Failure",
    probabilityPercent: 78,
    predictedFailureDate: "2024-03-15T00:00:00Z",
    confidenceLevel: "high",
    estimatedCost: 450000,
    recommendedAction: "Schedule compressor inspection and replacement",
    riskLevel: "high",
    daysUntilFailure: 45,
    impactedUnits: ["1A", "1B", "2A", "2B", "3A", "3B"],
  },
  {
    equipmentId: "eq_002",
    equipmentName: "Elevator System - Main",
    failureType: "Motor Bearing Wear",
    probabilityPercent: 65,
    predictedFailureDate: "2024-04-20T00:00:00Z",
    confidenceLevel: "medium",
    estimatedCost: 180000,
    recommendedAction: "Replace motor bearings during next maintenance window",
    riskLevel: "medium",
    daysUntilFailure: 81,
    impactedUnits: ["All floors 1-8"],
  },
  {
    equipmentId: "eq_003",
    equipmentName: "Water Heater - Building B",
    failureType: "Heating Element Degradation",
    probabilityPercent: 35,
    predictedFailureDate: "2024-07-10T00:00:00Z",
    confidenceLevel: "low",
    estimatedCost: 85000,
    recommendedAction: "Monitor temperature efficiency, schedule element inspection",
    riskLevel: "low",
    daysUntilFailure: 162,
    impactedUnits: ["4A", "4B", "5A", "5B"],
  },
  {
    equipmentId: "eq_004",
    equipmentName: "Fire Safety System",
    failureType: "Pump Seal Deterioration",
    probabilityPercent: 82,
    predictedFailureDate: "2024-02-28T00:00:00Z",
    confidenceLevel: "high",
    estimatedCost: 125000,
    recommendedAction: "Immediate pump seal replacement required",
    riskLevel: "critical",
    daysUntilFailure: 29,
    impactedUnits: ["All building areas"],
  },
]

export const mockMaintenanceSchedule = [
  {
    id: "pm_001",
    equipmentId: "eq_001",
    equipmentName: "Main HVAC System - Building A",
    taskType: "Preventive Maintenance",
    description: "Compressor inspection and refrigerant level check",
    scheduledDate: "2024-02-15T10:00:00Z",
    estimatedDuration: 4, // hours
    requiredSkills: ["HVAC Technician", "Refrigeration Specialist"],
    assignedTechnicians: ["Mike Rodriguez", "David Chen"],
    priority: "high",
    cost: 35000,
    status: "scheduled",
  },
  {
    id: "pm_002",
    equipmentId: "eq_002",
    equipmentName: "Elevator System - Main",
    taskType: "Predictive Maintenance",
    description: "Motor bearing replacement based on ML prediction",
    scheduledDate: "2024-03-10T08:00:00Z",
    estimatedDuration: 8,
    requiredSkills: ["Elevator Technician", "Mechanical Engineer"],
    assignedTechnicians: ["Lisa Park"],
    priority: "medium",
    cost: 180000,
    status: "planned",
  },
  {
    id: "pm_003",
    equipmentId: "eq_004",
    equipmentName: "Fire Safety System",
    taskType: "Emergency Maintenance",
    description: "Critical pump seal replacement",
    scheduledDate: "2024-01-25T06:00:00Z",
    estimatedDuration: 6,
    requiredSkills: ["Fire Safety Technician", "Pump Specialist"],
    assignedTechnicians: ["Emergency Contractor"],
    priority: "critical",
    cost: 125000,
    status: "urgent",
  },
]

export const mockManpowerPlanning = {
  currentStaff: [
    {
      id: "tech_001",
      name: "Mike Rodriguez",
      role: "HVAC Technician",
      skills: ["HVAC", "Refrigeration", "Electrical"],
      availability: "available",
      currentWorkload: 75, // percentage
      certifications: ["EPA 608", "NATE Certified"],
      hourlyRate: 1250,
    },
    {
      id: "tech_002",
      name: "David Chen",
      role: "Mechanical Engineer",
      skills: ["Mechanical", "Elevator", "HVAC"],
      availability: "busy",
      currentWorkload: 90,
      certifications: ["PE License", "Elevator Inspector"],
      hourlyRate: 1875,
    },
    {
      id: "tech_003",
      name: "Lisa Park",
      role: "Electrical Technician",
      skills: ["Electrical", "Fire Safety", "Security"],
      availability: "available",
      currentWorkload: 60,
      certifications: ["Master Electrician", "Fire Alarm Certified"],
      hourlyRate: 1500,
    },
  ],
  staffingRecommendations: [
    {
      period: "Next 30 days",
      requiredSkills: ["HVAC Technician", "Fire Safety Specialist"],
      recommendedAction: "Hire 1 additional HVAC technician",
      reasoning: "High probability HVAC failure and critical fire system maintenance",
      estimatedCost: 187500, // monthly cost
      urgency: "high",
    },
    {
      period: "Next 90 days",
      requiredSkills: ["Elevator Technician"],
      recommendedAction: "Contract elevator specialist for 2 weeks",
      reasoning: "Predicted elevator motor bearing failure",
      estimatedCost: 350000,
      urgency: "medium",
    },
  ],
  workloadForecast: [
    { month: "Feb", plannedHours: 320, availableHours: 280, utilizationRate: 114 },
    { month: "Mar", plannedHours: 280, availableHours: 320, utilizationRate: 88 },
    { month: "Apr", plannedHours: 360, availableHours: 320, utilizationRate: 113 },
    { month: "May", plannedHours: 240, availableHours: 320, utilizationRate: 75 },
  ],
}
